[CmdletBinding()]
param(
    [string]$Workspace = (Get-Location).Path,
    [switch]$KeepArtifacts
)

$ErrorActionPreference = "Continue"

$dogfoodRoot = Join-Path $env:TEMP "codex-windows-dogfood"
$runId = Get-Date -Format "yyyyMMdd-HHmmss"
$runDir = Join-Path $dogfoodRoot $runId
$fixtureDir = Join-Path $runDir "fixtures"

New-Item -ItemType Directory -Force -Path $fixtureDir | Out-Null

function Invoke-Capture {
    param(
        [Parameter(Mandatory = $true)][string]$File,
        [string[]]$Arguments = @(),
        [string]$WorkingDirectory
    )

    try {
        if ($WorkingDirectory) {
            $output = & $File @Arguments 2>&1 | ForEach-Object { $_.ToString() }
        } else {
            $output = & $File @Arguments 2>&1 | ForEach-Object { $_.ToString() }
        }
        return [ordered]@{
            ok = ($LASTEXITCODE -eq 0)
            exitCode = $LASTEXITCODE
            output = ($output -join "`n")
        }
    } catch {
        return [ordered]@{
            ok = $false
            exitCode = $null
            output = $_.Exception.Message
        }
    }
}

function Add-Case {
    param(
        [string]$Id,
        [string]$Section,
        [string]$Signature,
        [string]$Target,
        [string]$Actual,
        [string]$Evidence,
        [string]$Command,
        [string]$Conclusion,
        [string]$NeedsUpdate,
        [object]$Details = $null
    )

    [ordered]@{
        caseId = $Id
        section = $Section
        signature = $Signature
        targetLevel = $Target
        actualLevel = $Actual
        evidence = $Evidence
        localCommand = $Command
        conclusion = $Conclusion
        needsGuideOrSkillUpdate = $NeedsUpdate
        details = $Details
    }
}

function Run-Git {
    param([string]$Repo, [string[]]$GitArguments)
    return Invoke-Capture -File "git" -Arguments (@("-C", $Repo) + $GitArguments)
}

function New-Repo {
    param([string]$Name)
    $path = Join-Path $fixtureDir $Name
    New-Item -ItemType Directory -Force -Path $path | Out-Null
    Invoke-Capture -File "git" -Arguments @("init", $path) | Out-Null
    return $path
}

function Commit-Empty {
    param([string]$Repo, [string]$Message)
    return Invoke-Capture -File "git" -Arguments @(
        "-C", $Repo,
        "-c", "user.name=Codex Dogfood",
        "-c", "user.email=codex-dogfood@example.invalid",
        "commit", "--allow-empty", "-m", $Message
    )
}

function Test-ConfigFixture {
    $configDir = Join-Path $fixtureDir "config-corruption"
    New-Item -ItemType Directory -Force -Path $configDir | Out-Null
    $nulPath = Join-Path $configDir "config-nul.toml"
    $badPath = Join-Path $configDir "config-bad.toml"
    [System.IO.File]::WriteAllBytes($nulPath, [byte[]](0,0,0,0,0,0))
    Set-Content -LiteralPath $badPath -Value "sandbox_mode `"workspace-write`"" -Encoding UTF8

    $nulBytes = [System.IO.File]::ReadAllBytes($nulPath)
    $badText = Get-Content -Raw -LiteralPath $badPath
    return [ordered]@{
        nulPath = $nulPath
        nulDetected = ($nulBytes -contains 0)
        badPath = $badPath
        missingEqualsDetected = ($badText -notmatch "=")
    }
}

function New-IssueDraftFixture {
    param([object[]]$Cases)
    $draftDir = Join-Path $fixtureDir "issue-draft"
    New-Item -ItemType Directory -Force -Path $draftDir | Out-Null
    $draftPath = Join-Path $draftDir "codex-windows-issue-draft.md"
    $body = @(
        '# Codex Windows dogfood issue draft'
        ""
        '## Symptom'
        ""
        'Worktree setup failed with `fatal: invalid reference: master`.'
        ""
        '## Environment'
        ""
        '- Windows diagnostics: redacted; generated by local dogfood runner.'
        '- Workspace path: `[REDACTED]`'
        ""
        '## Key evidence'
        ""
        '- `git status --short --branch`: `## No commits yet on master`'
        '- `git rev-parse --verify master`: `fatal: Needed a single revision`'
        '- `git worktree list --porcelain`: `HEAD 0000000000000000000000000000000000000000`'
        ""
        '## Expected'
        ""
        'Codex should detect unborn branches before attempting detached worktree creation and explain that an initial commit is required.'
    )
    Set-Content -LiteralPath $draftPath -Value $body -Encoding UTF8
    return [ordered]@{
        path = $draftPath
        redacted = ((Get-Content -Raw -LiteralPath $draftPath) -notmatch [regex]::Escape($env:USERPROFILE))
        bytes = (Get-Item -LiteralPath $draftPath).Length
    }
}

function Get-IssueEvidence {
    param([int[]]$Numbers)
    $items = @()
    foreach ($number in $Numbers) {
        $view = Invoke-Capture -File "gh" -Arguments @(
            "issue", "view", $number.ToString(),
            "--repo", "openai/codex",
            "--json", "number,title,state,url,updatedAt"
        )
        if (-not $view.ok) {
            Start-Sleep -Milliseconds 500
            $view = Invoke-Capture -File "gh" -Arguments @(
                "issue", "view", $number.ToString(),
                "--repo", "openai/codex",
                "--json", "number,title,state,url,updatedAt"
            )
        }
        if ($view.ok -and $view.output) {
            try {
                $items += ($view.output | ConvertFrom-Json)
            } catch {
                $items += [ordered]@{ number = $number; state = "parse-failed"; url = "https://github.com/openai/codex/issues/$number" }
            }
        } else {
            $items += [ordered]@{ number = $number; state = "gh-failed"; url = "https://github.com/openai/codex/issues/$number"; error = $view.output }
        }
    }
    return $items
}

function Format-IssueStates {
    param([object[]]$Items)
    return (($Items | ForEach-Object { "#$($_.number)=$($_.state)" }) -join ", ")
}

$cases = @()
$workspaceExists = Test-Path -LiteralPath $Workspace
$diag = $null
if ($workspaceExists) {
    $diagScript = Join-Path (Split-Path -Parent $PSScriptRoot) "scripts\collect-codex-windows-diagnostics.ps1"
    if (-not (Test-Path -LiteralPath $diagScript)) {
        $diagScript = Join-Path $PSScriptRoot "collect-codex-windows-diagnostics.ps1"
    }
    $diagPath = Join-Path $runDir "diagnostics.json"
    & powershell -NoProfile -ExecutionPolicy Bypass -File $diagScript -Workspace $Workspace -OutputPath $diagPath | Out-Null
    if (Test-Path -LiteralPath $diagPath) {
        $diag = Get-Content -Raw -LiteralPath $diagPath | ConvertFrom-Json
    }
}

# C001: three safe Git worktree fixtures.
$c001Details = [ordered]@{}
$emptyRepo = New-Repo "c001-empty-unborn"
$emptyWorktree = Join-Path $fixtureDir "c001-empty-unborn-worktree"
$c001Details.emptyUnborn = [ordered]@{
    status = (Run-Git -Repo $emptyRepo -GitArguments @("status", "--short", "--branch")).output
    worktreeAdd = (Invoke-Capture -File "git" -Arguments @("-C", $emptyRepo, "worktree", "add", "--detach", $emptyWorktree, "master")).output
}

$noMainRepo = New-Repo "c001-no-main"
Commit-Empty -Repo $noMainRepo -Message "Initial commit" | Out-Null
$initialBranch = (Run-Git -Repo $noMainRepo -GitArguments @("symbolic-ref", "--short", "HEAD")).output.Trim()
Run-Git -Repo $noMainRepo -GitArguments @("branch", "production") | Out-Null
Run-Git -Repo $noMainRepo -GitArguments @("switch", "production") | Out-Null
if ($initialBranch) {
    Run-Git -Repo $noMainRepo -GitArguments @("branch", "-D", $initialBranch) | Out-Null
}
$missingDefaultRef = if ($initialBranch -eq "main") { "main" } else { "main" }
$c001Details.noMain = [ordered]@{
    branches = (Run-Git -Repo $noMainRepo -GitArguments @("branch", "-a")).output
    missingRef = $missingDefaultRef
    worktreeAdd = (Invoke-Capture -File "git" -Arguments @("-C", $noMainRepo, "worktree", "add", "--detach", (Join-Path $fixtureDir "c001-no-main-worktree"), $missingDefaultRef)).output
}

$remoteOnlyRepo = New-Repo "c001-remote-only"
Commit-Empty -Repo $remoteOnlyRepo -Message "Initial commit" | Out-Null
$head = (Run-Git -Repo $remoteOnlyRepo -GitArguments @("rev-parse", "HEAD")).output.Trim()
Run-Git -Repo $remoteOnlyRepo -GitArguments @("update-ref", "refs/remotes/origin/feature/dogfood", $head) | Out-Null
$c001Details.remoteOnly = [ordered]@{
    verifyShort = (Run-Git -Repo $remoteOnlyRepo -GitArguments @("rev-parse", "--verify", "feature/dogfood")).output
    verifyRemote = (Run-Git -Repo $remoteOnlyRepo -GitArguments @("rev-parse", "--verify", "origin/feature/dogfood")).output
    worktreeAdd = (Invoke-Capture -File "git" -Arguments @("-C", $remoteOnlyRepo, "worktree", "add", "--detach", (Join-Path $fixtureDir "c001-remote-only-worktree"), "feature/dogfood")).output
}
$cases += Add-Case -Id "C001" -Section "2. Worktree 创建失败" -Signature "fatal: invalid reference: master/main/feature" -Target "L2" -Actual "L2" -Evidence "local fixture plus GitHub #12346/#22635" -Command "git worktree add --detach <tmp> <ref>" -Conclusion "已验证：unborn branch、无 main、本地缺 remote-only 短名都会触发 invalid reference。" -NeedsUpdate "已补指南和 skill；本轮无需再补。" -Details $c001Details

$issueWorktree = Get-IssueEvidence -Numbers @(12346, 22635)
$issuePlugins = Get-IssueEvidence -Numbers @(26536, 26501, 25220, 26109, 22114)
$issueWin10 = Get-IssueEvidence -Numbers @(25178, 25411)
$issue740 = Get-IssueEvidence -Numbers @(24050, 26477, 26158)
$issueSandboxOther = Get-IssueEvidence -Numbers @(18620, 26438, 23194)
$issueNetwork = Get-IssueEvidence -Numbers @(18675, 25207, 25117)
$issueWsl = Get-IssueEvidence -Numbers @(25216, 22759, 22376, 24884, 26096)
$issueShell = Get-IssueEvidence -Numbers @(13917, 19629, 16268)
$issueSessions = Get-IssueEvidence -Numbers @(22004, 25430, 26104)
$issueUi = Get-IssueEvidence -Numbers @(25513, 20867, 26401)
$issueConfig = Get-IssueEvidence -Numbers @(26421)
$issueCrash = Get-IssueEvidence -Numbers @(19352, 25912)
$issueAv = Get-IssueEvidence -Numbers @(25425, 26194, 26218)
$issueStore = Get-IssueEvidence -Numbers @(17491)

$marketplaceExists = if ($diag) { [bool]$diag.codexFiles.bundledMarketplaceExists } else { $false }
$pluginCacheExists = if ($diag) { [bool]$diag.codexFiles.pluginCacheExists } else { $false }
$cases += Add-Case -Id "C002" -Section "3. Computer Use / Browser 插件不可用" -Signature "Computer Use plugins unavailable / marketplace missing" -Target "L1" -Actual "L1" -Evidence (Format-IssueStates $issuePlugins) -Command "Test-Path bundled marketplace; inspect plugin cache/processes" -Conclusion "部分验证：本机只读检查完成；marketplaceExists=$marketplaceExists, pluginCacheExists=$pluginCacheExists。未删除或重建缓存。" -NeedsUpdate "不需要。"

$osBuild = if ($diag -and $diag.os) { $diag.os.osBuildNumber } else { "" }
$cases += Add-Case -Id "C003" -Section "4. Windows 10 Computer Use 截图失败" -Signature "SetIsBorderRequired failed 0x80004002" -Target "L0" -Actual "L0" -Evidence (Format-IssueStates $issueWin10) -Command "GitHub issue status + OS build check" -Conclusion "仅证据核查：本机 build=$osBuild；不是 Windows 10 专用复现矩阵，不做真实截图复现。" -NeedsUpdate "不需要。"

$setupHelpers = @()
try {
    if ($diag -and $diag.codexAppx -and $diag.codexAppx.InstallLocation) {
        $setupHelpers = @(Get-ChildItem -LiteralPath $diag.codexAppx.InstallLocation -Recurse -Filter "codex-windows-sandbox-setup.exe" -ErrorAction SilentlyContinue | Select-Object FullName, Length, LastWriteTime)
    }
} catch {}
$cases += Add-Case -Id "C004" -Section "5. spawn setup refresh / os error 740" -Signature "spawn setup refresh / os error 740" -Target "L1" -Actual "L1" -Evidence (Format-IssueStates $issue740) -Command "collect diagnostics; search app install for codex-windows-sandbox-setup.exe" -Conclusion "部分验证：本机只读采集版本/config/helper 线索；helperCount=$($setupHelpers.Count)。未切 sandbox、未改 manifest。" -NeedsUpdate "不需要。"

$cases += Add-Case -Id "C005" -Section "6. 其他 Windows sandbox 启动错误" -Signature "1326/1909, 1344, program not found" -Target "L1" -Actual "L1" -Evidence (Format-IssueStates $issueSandboxOther) -Command "collect diagnostics; inspect config/appx/codex doctor" -Conclusion "部分验证：本机未强制复现 sandbox 用户/DACL 错误；只读状态可用于 issue 模板。" -NeedsUpdate "不需要。"

$proxySet = if ($diag) { "HTTP=$($diag.environment.httpProxySet), HTTPS=$($diag.environment.httpsProxySet)" } else { "unknown" }
$cases += Add-Case -Id "C006" -Section "7. 网络、DNS、npm、代理" -Signature "sandbox DNS/npm/proxy failure" -Target "L1" -Actual "L1" -Evidence (Format-IssueStates $issueNetwork) -Command "inspect config preview and HTTP_PROXY/HTTPS_PROXY flags" -Conclusion "部分验证：只读检查完成，proxy=$proxySet。未修改代理或 network_access。" -NeedsUpdate "不需要。"

$wslSummary = if ($diag) { "statusOk=$($diag.wsl.status.ok), listOk=$($diag.wsl.list.ok), WSL_DISTRO_NAME=$($diag.environment.wslDistroName)" } else { "unknown" }
$cases += Add-Case -Id "C007" -Section "8. WSL / Windows 混合模式" -Signature "WSL path/CODEX_HOME split-brain" -Target "L1" -Actual "L1" -Evidence (Format-IssueStates $issueWsl) -Command "wsl --status; wsl -l -v; inspect CODEX_HOME/WSL_DISTRO_NAME" -Conclusion "部分验证：$wslSummary。未改 WSL 或 CODEX_HOME。" -NeedsUpdate "不需要。"

$psVersion = if ($diag) { $diag.powershell.version } else { "" }
$cases += Add-Case -Id "C008" -Section "9. PowerShell / Shell / 编码 / 用户名" -Signature "PowerShell host/encoding/execution policy" -Target "L1" -Actual "L1" -Evidence (Format-IssueStates $issueShell) -Command "Get-Command pwsh/powershell; Get-ExecutionPolicy -List; inspect username path" -Conclusion "部分验证：PowerShell=$psVersion；只读检查命令位置和执行策略。未改执行策略。" -NeedsUpdate "不需要。"

$largestSession = ""
if ($diag -and $diag.codexFiles.largestSessions -and $diag.codexFiles.largestSessions.Count -gt 0) {
    $largestSession = "$($diag.codexFiles.largestSessions[0].Length) bytes"
}
$cases += Add-Case -Id "C009" -Section "10. 长会话、历史记录、内存、启动崩溃" -Signature "RangeError / large session JSONL" -Target "L1" -Actual "L1" -Evidence (Format-IssueStates $issueSessions) -Command "scan %USERPROFILE%\\.codex\\sessions largest JSONL" -Conclusion "部分验证：已只读扫描 session 大小，largest=$largestSession。未移动历史。" -NeedsUpdate "不需要。"

$cases += Add-Case -Id "C010" -Section "11. UI 透明、最大化、卡顿" -Signature "maximized transparent/freezing UI" -Target "L0" -Actual "L0" -Evidence (Format-IssueStates $issueUi) -Command "GitHub issue status only" -Conclusion "仅证据核查：UI 症状需用户遇到时记录截图；本轮不操作桌面 UI。" -NeedsUpdate "不需要。"

$configFixture = Test-ConfigFixture
$cases += Add-Case -Id "C011" -Section "12. 配置文件损坏" -Signature "config.toml NUL / key with no value" -Target "L2" -Actual "L2" -Evidence (Format-IssueStates $issueConfig) -Command "create temp bad config fixtures; detect NUL and missing equals" -Conclusion "已验证：临时 fixture 可检测 NUL 和缺少等号的坏 TOML，不触碰真实 config。" -NeedsUpdate "可补脚本：未来可把 config corruption 检测并入 diagnostics。" -Details $configFixture

$crashCount = if ($diag -and $diag.codexFiles.crashCandidates) { $diag.codexFiles.crashCandidates.Count } else { 0 }
$cases += Add-Case -Id "C012" -Section "13. 启动空白、直接闪退、Crashpad dump" -Signature "blank/spinner/crashpad dump" -Target "L1" -Actual "L1" -Evidence (Format-IssueStates $issueCrash) -Command "readonly scan LOCALAPPDATA CrashDumps/Packages for codex/crashpad" -Conclusion "部分验证：Crash candidate count=$crashCount。未 repair/reset app。" -NeedsUpdate "不需要。"

$cases += Add-Case -Id "C013" -Section "14. 杀软/Defender/企业安全软件拦截" -Signature "Norton/Symantec/Defender blocks helper" -Target "L0" -Actual "L0" -Evidence (Format-IssueStates $issueAv) -Command "GitHub issue status only" -Conclusion "仅证据核查：不模拟恶意/混淆命令，不改白名单。" -NeedsUpdate "不需要。"

$appxVersion = if ($diag -and $diag.codexAppx) { $diag.codexAppx.Version } else { "" }
$arch = if ($diag) { $diag.environment.processorArchitecture } else { "" }
$cases += Add-Case -Id "C014" -Section "15. Microsoft Store / 安装位置 / ARM64" -Signature "Store install path / ARM64 / non-C drive" -Target "L1" -Actual "L1" -Evidence (Format-IssueStates $issueStore) -Command "Get-AppxPackage OpenAI.Codex; winget list --name Codex; inspect architecture" -Conclusion "部分验证：AppxVersion=$appxVersion, Arch=$arch。未改安装位置。" -NeedsUpdate "不需要。"

$draft = New-IssueDraftFixture -Cases $cases
$cases += Add-Case -Id "C015" -Section "16. 报告 issue 模板" -Signature "issue report completeness/redaction" -Target "L2" -Actual "L2" -Evidence "local fixture" -Command "generate temp redacted issue draft fixture" -Conclusion "已验证：生成脱敏 issue draft fixture，redacted=$($draft.redacted)，bytes=$($draft.bytes)。" -NeedsUpdate "不需要。" -Details $draft

$cases += Add-Case -Id "C016" -Section "17. 当前优先级" -Signature "P0/P1/P2 priority review" -Target "L0" -Actual "L0" -Evidence "C001-C015 dogfood outputs" -Command "review case outcomes against guide priority list" -Conclusion "仅证据核查：P0/P1/P2 与本轮证据一致；C001 保持 P1，P0 仍是 sandbox 740、plugin marketplace、large session。" -NeedsUpdate "不需要。"

$result = [ordered]@{
    runId = $runId
    generatedAt = (Get-Date).ToString("o")
    runDir = $runDir
    tempRoot = $dogfoodRoot
    workspace = $Workspace
    cleanup = if ($KeepArtifacts) { "kept" } else { "cleaned" }
    cases = $cases
}

$json = $result | ConvertTo-Json -Depth 12

if (-not $KeepArtifacts) {
    try {
        $resolvedRoot = [System.IO.Path]::GetFullPath($dogfoodRoot)
        $resolvedRun = [System.IO.Path]::GetFullPath($runDir)
        if ($resolvedRun.StartsWith($resolvedRoot, [System.StringComparison]::OrdinalIgnoreCase) -and (Test-Path -LiteralPath $runDir)) {
            Remove-Item -LiteralPath $runDir -Recurse -Force
        }
    } catch {
        # Cleanup failure is reported in JSON status by preserving the runDir value.
    }
}

Write-Output $json
